### ISSUE TITLE
Validating store prior to data retrieval

### ISSUE THREAD

**Issue by greghesp** [vetalas/shopify-app-firebase#4]
Perhaps not an issue, but this is similar to what I am trying to achieve.

When a user authenticates their app, it's easy enough to add the shop to a firestore document using the afterauth callback.

The problem I'm struggling to solve though, how do you validate that subsequent requests for data from Firestore are for the shop requesting it.

If you simply use the shopOrigin cookie, a user could just change that to any other store name and get data from Firestore for another store

**Comment by shvjds** [comment]
Hi, sorry for replying so late but we stopped working on this a long time ago and we won't be able to offer any suggestion. The only reason we were trying to do this in the first place was to have a fast prototyping option.
